# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclaw-1p-sdk-resolver" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "fcf9a683c932846c34bcc6ef95f3a9d96a5967dfb33447c851992f305c5da19c"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a50ca82110c4cb43cc15892fcbdc9ac3a81e777b88137cff6aa5546974c73a6c"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "openclaw-1p-sdk-resolver"
  desc "OpenClaw exec secrets provider backed by the official 1Password Go SDK"
  homepage "https://github.com/timshadel/openclaw-1p-sdk-resolver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openclaw-1p-sdk-resolver"

  # No zap stanza required

end
