# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclaw-1p-sdk-resolver" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "20b87889f4dafc387a9a8ce3b021cd5e994b215cfaef9c67e2dc6f9e9e11ab9a"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2b0a8377779b7c1507b17633ffcc5dccf3d781cd90cc514fb1c1db2cbdf4b8d"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "openclaw-1p-sdk-resolver"
  desc "OpenClaw exec secrets provider backed by the official 1Password Go SDK"
  homepage "https://github.com/timshadel/openclaw-1p-sdk-resolver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openclaw-1p-sdk-resolver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclaw-1p-sdk-resolver"]
    end
  end

  # No zap stanza required

end
