# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclaw-1p-sdk-resolver" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "fd9eb1677d9a98aaf0f8664a7c272711e0f2b1b1bc6557d66472cd4a0f1abb4a"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfd6bea5c56aea01a222ab192ddc43c32e134fc8edda290e8dd5c90d686a9754"
      url "https://github.com/timshadel/openclaw-1p-sdk-resolver/releases/download/v#{version}/openclaw-1p-sdk-resolver_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "openclaw-1p-sdk-resolver"
  desc "OpenClaw exec secrets provider backed by the official 1Password Go SDK"
  homepage "https://github.com/timshadel/openclaw-1p-sdk-resolver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openclaw-1p-sdk-resolver"

  # No zap stanza required

end
